# client/Dockerfile
FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig.json tailwind.config.ts postcss.config.mjs next.config.mjs ./
COPY public ./public
COPY src ./src

RUN bun install
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start"]
