FROM oven/bun:1

WORKDIR /app

# Accept build arguments
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_BACKEND_URL

# Make them available inside the container
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

COPY package.json bun.lock ./
COPY tsconfig.json tailwind.config.ts postcss.config.mjs next.config.mjs ./
COPY public ./public
COPY src ./src

RUN bun install

# At this point, NEXT_PUBLIC_*** envs are available 🎯
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start"]
