# server/Dockerfile
FROM oven/bun:1

# Install OpenSSL dependencies
RUN apt-get update && apt-get install -y openssl libssl-dev

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig.json ./
COPY prisma ./prisma
COPY public ./public
COPY src ./src

RUN bun install
RUN bun run build

EXPOSE 4000

CMD ["bun", "run", "start"]
